name: lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.5"]
        poetry-version: [1.1.0]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: lint codebase
        run: poetry run flake8 --ignore=E501,E402 .
